# Site settings
title: Satwik Mukherjee
# logo : 
show_downloads: true
# description: A simple website built with Jekyll
# baseurl: "/"

# Build settings
# markdown: kramdown
theme: jekyll-theme-minimal
